In [1]:
import numpy as np

Array Operations

Arithematic Operations

In [ ]:
arr1 = np.arange(1,6)
arr2 = np.arange(6,11)
print(arr1)
print(arr2)

[ 6  7  8  9 10]


In [6]:
arr1 + arr2

array([ 7,  9, 11, 13, 15])

In [7]:
arr1 - arr2

array([-5, -5, -5, -5, -5])

In [8]:
arr1 * arr2

array([ 6, 14, 24, 36, 50])

In [9]:
arr1 ** arr2

array([      1,     128,    6561,  262144, 9765625])

In [10]:
arr1 / arr2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [11]:
arr1 // arr2

array([0, 0, 0, 0, 0])