In [1]:
import numpy as np

Array Indexing and Slicing

In [2]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [3]:
arr[6]

np.int64(17)

In [4]:
arr[1:3]

array([12, 13])

Numpy Indexing and Slicing of Matrix

In [7]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [8]:
arr[0]

array([1, 2, 3, 4, 5])

In [9]:
arr[0][1]

np.int64(2)

In [16]:
arr[0,0]

np.int64(1)

In [24]:
arr[0:6, 0:1]

array([[ 1],
       [ 6],
       [11],
       [16],
       [21],
       [26]])

Boolean Indexing

In [31]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [32]:
bool_index = arr%2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [33]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])