In [1]:
import numpy as np

Arrays

In [4]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [6]:
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [7]:
arr = np.zeros((6,6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [9]:
arr = np.ones(6)
arr

array([1., 1., 1., 1., 1., 1.])

In [11]:
arr = np.linspace(1,10,5)
arr

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

Random Generation

In [13]:
arr = np.random.rand(5)
arr

array([0.74813347, 0.09802747, 0.78033799, 0.51929525, 0.11985335])

In [15]:
arr = np.random.randn(10)
arr

array([ 0.66568945, -1.17865182, -0.11832894, -0.04855637,  1.05789377,
       -0.60241832, -1.74424427,  0.35338654, -0.51339395,  2.54084786])

In [19]:
arr = np.random.randint(0,10,20)
arr

array([8, 6, 9, 3, 5, 7, 6, 2, 0, 5, 6, 8, 8, 6, 7, 3, 8, 2, 2, 0])

Array Attributes

In [20]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
arr.shape

(3, 3)

In [22]:
arr.size

9

In [23]:
arr.dtype

dtype('int64')

Array Methods

In [24]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
arr.min()

np.int64(1)

In [27]:
arr.max()

np.int64(9)

In [28]:
arr.sum()

np.int64(45)

In [ ]:
np.sum(arr,axis=0) #COLS

array([12, 15, 18])

In [30]:
np.sum(arr,axis=1) #ROWS

array([ 6, 15, 24])

In [31]:
arr.mean()

np.float64(5.0)

In [32]:
arr.std()

np.float64(2.581988897471611)

In [34]:
arr.argmax()

np.int64(8)

In [35]:
arr.argmin()

np.int64(0)

Reshaping and Resizing

In [38]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [43]:
arr = arr.reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [42]:
arr = arr.reshape(5,6)
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])